BEGIN;

CREATE TABLE tqm_text_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  entry_id uuid NOT NULL PRIMARY KEY,
  text TEXT NOT NULL,
  user_id uuid NOT NULL,
  date_created TIMESTAMP NOT NULL
);

CREATE TABLE tqm_audio_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  entry_id uuid NOT NULL PRIMARY KEY,
  text TEXT NOT NULL,
  user_id uuid NOT NULL,
  date_created TIMESTAMP NOT NULL
);

CREATE TABLE tqm_video_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  entry_id uuid NOT NULL PRIMARY KEY,
  text TEXT NOT NULL,
  user_id uuid NOT NULL,
  date_created TIMESTAMP NOT NULL
);

CREATE TABLE tqm_file_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  entry_id uuid NOT NULL PRIMARY KEY,
  text TEXT NOT NULL,
  user_id uuid NOT NULL,
  date_created TIMESTAMP NOT NULL
);

COMMIT;