BEGIN;

CREATE TABLE tqm_text_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  entry_id uuid NOT NULL PRIMARY KEY,
  text TEXT NOT NULL,
  user_id uuid NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TABLE tqm_file_uploads (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  entry_id uuid NOT NULL PRIMARY KEY,
  file_name TEXT NOT NULL,
  file_path TEXT NOT NULL,
  file_type TEXT NOT NULL,
  user_id uuid NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL
);

COMMIT;