CREATE TABLE tqm_user_relationship (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  relationship_id uuid NOT NULL PRIMARY KEY,
  user_id uuid REFERENCES tqm_users(user_id) NOT NULL,
  partner_id uuid REFERENCES tqm_users(user_id) NOT NULL,
  anniversary TIMESTAMP NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TABLE tqm_relationship_request (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid PRIMARY KEY NOT NULL,
  user_first_name TEXT NOT NULL,
  user_last_name TEXT NOT NULL,
  user_email TEXT NOT NULL,
  partner_id uuid NOT NULL,
  partner_first_name TEXT NOT NULL,
  partner_last_name TEXT NOT NULL,
  partner_email TEXT NOT NULL,
  anniversary TIMESTAMP NOT NULL
);