CREATE TABLE tqm_gen_questions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  question_id uuid PRIMARY KEY NOT NULL,
  question TEXT NOT NULL,
  category TEXT NOT NULL,
  section TEXT NOT NULL,
  user_id uuid REFERENCES tqm_users(user_id),
  date_created TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TABLE tqm_questionaire (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  entry_id uuid PRIMARY KEY NOT NULL,
  user_id uuid REFERENCES tqm_users(user_id),
  relationship_id uuid REFERENCES tqm_user_relationship(relationship_id),
  question_id uuid REFERENCES tqm_gen_questions(question_id) NOT NULL,
  joy INTEGER NOT NULL,
  disgust INTEGER NOT NULL,
  sadness INTEGER NOT NULL,
  anger INTEGER NOT NULL,
  fear INTEGER NOT NULL,
  mood INTEGER NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL
);


