CREATE TABLE tqm_relationship_request (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid PRIMARY KEY NOT NULL,
  user_first_name TEXT NOT NULL,
  user_last_name TEXT NOT NULL,
  user_email TEXT NOT NULL,
  partner_id uuid NOT NULL,
  partner_first_name TEXT NOT NULL,
  partner_last_name TEXT NOT NULL,
  partner_email TEXT NOT NULL
);